version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./build:/code
            - ./dockerised-php/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./build:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
